services:
  ai-experiments:
    image: ai-experiments:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: nvidia/cuda
        BASE_TAG: 11.8.0-devel-ubuntu22.04
        CONTAINER_USER: ${USER}
    container_name: ai-experiments
    hostname: ai-experiments
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../:/workspace:rw
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /workspace
    command: /bin/bash
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
